// Code generated by "stringer -type Literal tokens.go"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Int-0]
	_ = x[Float-1]
	_ = x[Char-2]
	_ = x[String-3]
}

const _Literal_name = "IntFloatCharString"

var _Literal_index = [...]uint8{0, 3, 8, 12, 18}

func (i Literal) String() string {
	if i >= Literal(len(_Literal_index)-1) {
		return "Literal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Literal_name[_Literal_index[i]:_Literal_index[i+1]]
}
