// Code generated by "stringer -type Operator -linecomment tokens.go"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Not-1]
	_ = x[LNot-2]
	_ = x[Inc-3]
	_ = x[Dec-4]
	_ = x[Deref-5]
	_ = x[OrOr-6]
	_ = x[AndAnd-7]
	_ = x[Eql-8]
	_ = x[Neq-9]
	_ = x[Lss-10]
	_ = x[Leq-11]
	_ = x[Gtr-12]
	_ = x[Geq-13]
	_ = x[Add-14]
	_ = x[Sub-15]
	_ = x[Or-16]
	_ = x[Xor-17]
	_ = x[Mul-18]
	_ = x[Div-19]
	_ = x[Rem-20]
	_ = x[And-21]
	_ = x[Shl-22]
	_ = x[Shr-23]
	_ = x[OperatorMax-24]
}

const _Operator_name = "~!++--.*||&&==!=<<=>>=+-|^*/%&<<>>OperatorMax"

var _Operator_index = [...]uint8{0, 1, 2, 4, 6, 8, 10, 12, 14, 16, 17, 19, 20, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32, 34, 45}

func (i Operator) String() string {
	i -= 1
	if i >= Operator(len(_Operator_index)-1) {
		return "Operator(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Operator_name[_Operator_index[i]:_Operator_index[i+1]]
}
