// Code generated by "stringer -type token -linecomment tokens.go"; DO NOT EDIT.

package syntax

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_EOF-1]
	_ = x[_Name-2]
	_ = x[_Literal-3]
	_ = x[_Operator-4]
	_ = x[_AssignOp-5]
	_ = x[_Assign-6]
	_ = x[_Star-7]
	_ = x[_Lparen-8]
	_ = x[_Lbrack-9]
	_ = x[_Lbrace-10]
	_ = x[_Rparen-11]
	_ = x[_Rbrack-12]
	_ = x[_Rbrace-13]
	_ = x[_Comma-14]
	_ = x[_Semi-15]
	_ = x[_Colon-16]
	_ = x[_Dot-17]
	_ = x[_Cond-18]
	_ = x[keywordFirst-19]
	_ = x[_Const-20]
	_ = x[_Proc-21]
	_ = x[_Return-22]
	_ = x[_Struct-23]
	_ = x[_Var-24]
	_ = x[keywordLast-25]
}

const _token_name = "EOFnameliteralopop==*([{)]},;:.?constprocreturnstructvar"

var _token_index = [...]uint8{0, 3, 7, 14, 16, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 32, 37, 41, 47, 53, 56, 56}

func (i token) String() string {
	i -= 1
	if i >= token(len(_token_index)-1) {
		return "token(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _token_name[_token_index[i]:_token_index[i+1]]
}
